name: gene_family_evolution
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8
  - numpy=1.21.0
  - pandas=1.3.0
  - orthofinder=3.0.1b1
  - hmmer=3.4
  - seqkit=2.9.0
  - biopython
  - r-base=4.3.1
  - r-data.table
  - r-coda
  - r-tidyverse
  - r-BiocManager
  - r-patchwork
  - r-stringr
  - r-foreach
  - r-seqinr
  - r-optparse
  - r-phytools
  - r-ape
  - r-viridis
  - r-readxl
  - r-phylotools
  - openmpi
  - gcc
  - gxx_linux-64
  - libxml2
  - libgit2
  - fontconfig
  - harfbuzz
  - fribidi
  - freetype
  - jpeg
  - glpk
  - gmp
  - mpfr
  - mafft
  - iqtree
  - samtools
